-- ==============================================================================
-- Migration 02: Enterprise Cloud Security, PIN Protection, Anti-Wipe Shield & Cloud Backups
-- ==============================================================================

-- 1. إضافة أعمدة الحماية (بصمة الرمز السري SHA-256 ورقم النسخة) إلى الجدول الرئيسي
ALTER TABLE public.mizan_cloud_sync
  ADD COLUMN IF NOT EXISTS pin_hash TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS sync_version INTEGER DEFAULT 1;

-- 2. إلغاء صلاحية الحذف العشوائي (DELETE) من الجدول الرئيسي لحماية بيانات المدارس
DROP POLICY IF EXISTS "Allow delete for all mizan_cloud_sync" ON public.mizan_cloud_sync;

-- 3. إنشاء جدول النسخ الاحتياطية السحابية التلقائية (Cloud Backups History)
CREATE TABLE IF NOT EXISTS public.mizan_cloud_backups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_code TEXT NOT NULL,
  school_name TEXT DEFAULT '',
  school_level TEXT DEFAULT 'primary',
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_by TEXT DEFAULT 'الكنترول',
  pin_hash TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mizan_backups_school_code
  ON public.mizan_cloud_backups (school_code, created_at DESC);

ALTER TABLE public.mizan_cloud_backups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select mizan_cloud_backups" ON public.mizan_cloud_backups;
CREATE POLICY "Allow select mizan_cloud_backups"
  ON public.mizan_cloud_backups FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow insert mizan_cloud_backups" ON public.mizan_cloud_backups;
CREATE POLICY "Allow insert mizan_cloud_backups"
  ON public.mizan_cloud_backups FOR INSERT TO anon, authenticated WITH CHECK (true);

-- 4. دالة الحماية السحابية الصارمة على مستوى قاعدة البيانات (PIN Verification + Anti-Wipe + Auto Backup)
CREATE OR REPLACE FUNCTION public.fn_protect_mizan_cloud_sync()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  old_students_count INT := 0;
  new_students_count INT := 0;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    -- أ) التحقق من الرمز السري للمدرسة (إذا كان محدداً مسبقاً)
    IF COALESCE(OLD.pin_hash, '') <> '' AND COALESCE(NEW.pin_hash, '') <> OLD.pin_hash THEN
      RAISE EXCEPTION 'INVALID_CLOUD_PIN: الرمز السري للسحابة غير مطابق لرمز المدرسة المحمي';
    END IF;

    -- إذا لم يرسل التحديث رمزاً جديداً وكان القديم فارغاً أو مطابقاً، نحتفظ بالرمز المحمي
    IF COALESCE(NEW.pin_hash, '') = '' AND COALESCE(OLD.pin_hash, '') <> '' THEN
      NEW.pin_hash := OLD.pin_hash;
    END IF;

    -- ب) درع منع المسح الكارثي (Anti-Wipe Shield): منع جهاز فارغ من مسح سجل يحتوي على طلبة
    IF JSONB_TYPEOF(OLD.payload->'students') = 'array' THEN
      old_students_count := JSONB_ARRAY_LENGTH(OLD.payload->'students');
    END IF;
    IF JSONB_TYPEOF(NEW.payload->'students') = 'array' THEN
      new_students_count := JSONB_ARRAY_LENGTH(NEW.payload->'students');
    END IF;

    IF old_students_count > 0 AND new_students_count = 0 AND COALESCE((NEW.payload->>'allowEmptyOverwrite')::boolean, false) = false THEN
      RAISE EXCEPTION 'EMPTY_OVERWRITE_BLOCKED: تم حظر مسح بيانات الطلبة من جهاز فارغ لحماية السجل السحابي';
    END IF;

    -- ج) زيادة رقم إصدار المزامنة تلقائياً
    NEW.sync_version := COALESCE(OLD.sync_version, 1) + 1;

    -- د) حفظ نسخة احتياطية سحابية تلقائية قبل التحديث (بشرط وجود طلبة)
    IF old_students_count > 0 THEN
      INSERT INTO public.mizan_cloud_backups (school_code, school_name, school_level, payload, updated_by, pin_hash)
      VALUES (OLD.school_code, OLD.school_name, OLD.school_level, OLD.payload, OLD.updated_by, OLD.pin_hash);

      -- الاحتفاظ بآخر 15 نسخة احتياطية فقط لكل مدرسة لتوفير المساحة السحابية
      DELETE FROM public.mizan_cloud_backups
      WHERE id IN (
        SELECT id FROM public.mizan_cloud_backups
        WHERE school_code = OLD.school_code
        ORDER BY created_at DESC
        OFFSET 15
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_mizan_cloud_sync ON public.mizan_cloud_sync;
CREATE TRIGGER trg_protect_mizan_cloud_sync
  BEFORE INSERT OR UPDATE ON public.mizan_cloud_sync
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_protect_mizan_cloud_sync();
